name: Concatenate Flash Cards and Update Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  concatenate_and_update_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Concatenate Flash Cards
        shell: bash
        run: |
          bash concat.sh 
        working-directory: ${{ github.workspace }}
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update release
        shell: bash
        run: |
          cd release
          for file in *.txt; do
            gh release upload cards $file --clobber  
          done
        working-directory: ${{ github.workspace }}
        env: 
          GITHUB_TOKEN: ${{ github.token }}
